name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker image
      run: |
        docker build -t alishba567/python-auth-example .
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push alishba567/python-auth-example
